export enum WSMessageTypeEnum {
  INFO = 'INFO',
  ERROR = 'ERROR',
  ROOM_STATE_CHANGED = 'ROOM_STATE_CHANGED',
  START_GAME = 'START_GAME',
  CHALLENGER = 'CHALLENGER',
}

export enum ChallengerMessageTypeEnum {
  INIT_GAME = 'INIT_GAME',
  END_GAME = 'END_GAME',
  REFRESH = 'REFRESH',
  BUILD_DECK = 'BUILD_DECK',
  READY_BATTLE = 'READY_BATTLE',
  DISCARD_CARD = 'DISCARD_CARD',
}
